services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: mw
      POSTGRES_PASSWORD: mw
      POSTGRES_DB: memberworks
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
volumes: { pgdata: {} }
